In [1]:
import numpy as np

#addition
np.add(45,20)

65

In [3]:
#subtraction
np.subtract(45,23)

22

In [4]:
#ndarray multiplication
#create ndarray which contains number of hrs worked for 5 days
#hourly rate is 15 usd
np_daily_wage = np.array([7,9,13,8,11])*15

In [5]:
print np_daily_wage

[105 135 195 120 165]


In [6]:
sum(np_daily_wage)

720

Comparison Operations

In [8]:
#comparison ndarray for weely hrs, 5 consecutive weeks hrs data
np_weekly_hrs = np.array([23,41,55,47,38])

#week with more than 40 hours
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [9]:
#week with more not equals to 40 hours
np_weekly_hrs[np_weekly_hrs!=40]

array([23, 41, 55, 47, 38])

Logical Operations

In [10]:
#Logical And Operations
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])