In [2]:
import numpy as np

np_sqrt = np.sqrt([2,4,9,16])

np_sqrt

array([1.41421356, 2.        , 3.        , 4.        ])

In [3]:
from numpy import pi
np.cos(pi)

-1.0

In [4]:
np.sin(pi/2)

1.0

In [5]:
np.floor([1.5,1.6,2.7,3.3,1.1,-0.3,-1.4])

array([ 1.,  1.,  2.,  3.,  1., -1., -2.])

In [6]:
np.exp([0,1,5])

array([  1.        ,   2.71828183, 148.4131591 ])

Shape Manipulation Example

In [8]:
#new array
new_cyclist_trials = np.array([[10,15,17,26,13,19],[12,11,21,24,14,23]])

#ravel flattens the dataset in 1 row
new_cyclist_trials.ravel()

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

In [9]:
#reshape can change the dataset to different rows and columns
new_cyclist_trials.reshape(3,4)

array([[10, 15, 17, 26],
       [13, 19, 12, 11],
       [21, 24, 14, 23]])

In [10]:
#resize can change it to its original dimensions
new_cyclist_trials.resize(2,6)

In [11]:
new_cyclist_trials

array([[10, 15, 17, 26, 13, 19],
       [12, 11, 21, 24, 14, 23]])

In [12]:
#split the array into two
np.hsplit(new_cyclist_trials,2)

[array([[10, 15, 17],
        [12, 11, 21]]), array([[26, 13, 19],
        [24, 14, 23]])]

In [14]:
new_cyclist_1 = np.array([10,15,17,26,13,19])
new_cyclist_2 = np.array([12,11,21,24,14,23])


In [15]:
#stacks the array together
np.hstack((new_cyclist_1,new_cyclist_2))

array([10, 15, 17, 26, 13, 19, 12, 11, 21, 24, 14, 23])

Broadcasting

In [16]:
#create two arrays of the same shape
array_a = np.array([2,3,5,8])
array_b = np.array([.3,.3,.3,.3])

In [17]:
#multiply arrays
array_a * array_b

array([0.6, 0.9, 1.5, 2.4])

In [18]:
#create a variable with a scalar value
scalar_c = .3

In [19]:
#multiply ID array with a scalar value
array_a * scalar_c

array([0.6, 0.9, 1.5, 2.4])

In [20]:
np_week_one = np.array([105,135,195,120,165])
np_week_two = np.array([123,156,230,200,147])

In [21]:
total_earning = np_week_one + np_week_two

In [22]:
total_earning

array([228, 291, 425, 320, 312])

In [23]:
np_week_one_hrs = np_week_one/15

In [24]:
np_week_one_hrs

array([ 7,  9, 13,  8, 11])

Linear Algebra - Transpose

In [26]:
test_scores = np.array([[83,71,57,63],[54,68,81,45]])


In [27]:
test_scores.transpose()

array([[83, 54],
       [71, 68],
       [57, 81],
       [63, 45]])

Linear Algebra - Inverse and Trace Functions

In [28]:
inverse_array = np.array([[10,20],[15,25]])

In [30]:
#inverse can only be applied in a square matrix
np.linalg.inv(inverse_array)

array([[-0.5,  0.4],
       [ 0.3, -0.2]])

In [31]:
trace_array = np.array([[10,20],[22,31]])

In [32]:
#to get the sum of the diagonal elements 10 and 31
np.trace(trace_array)

41